# Generated by Django 3.0.7 on 2020-06-27 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200621_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='سرنام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک دسته\u200cبندی')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
                ('posision', models.IntegerField(verbose_name='چیدمان')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی ها',
                'ordering': ['posision'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'نگاشت', 'verbose_name_plural': 'نگاشت ها'},
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ نمایش'),
        ),
    ]
