# Generated by Django 3.0.7 on 2020-07-29 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200708_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleManager',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.Category', verbose_name='زیردسته'),
        ),
    ]
